FORMAT: 1A

# WMF Bidi

## Group People

### Get people [GET /people]

+ Response 200 (application/json)
    + Attributes (array)
        - (Person)
            + id: 1 (number)
            + firstName: `John` (string)
            + lastName: `Doe` (string)
            + email: `john@doe.com` (string)
        - (Person)
            + id: 2 (number)
            + firstName: `Jane` (string)
            + lastName: `Doe` (string)
            + email: `john@doe.com` (string)

# Data Structures

## Person (object)

+ id: 1 (number)
+ firstName: `John` (string)
+ lastName: `Doe` (string)
+ email: `john@doe.com` (string)